[build]
  base = "/opt/build/repo"  # Root directory for the project
  command = "echo 'No build command required'"  # No build step for static frontend
  publish = "/opt/build/repo/frontend"  # The folder that contains your frontend build (adjust based on where your index.html is)

[context.production.environment]
  VITE_BACKEND_URL = "https://bluejay-production.up.railway.app"  # Backend URL for the API, change accordingly

[[plugins]]
  package = "@netlify/plugin-functions-installation"  # Only needed if using Netlify functions

[[redirects]]
  # Example redirects if needed in future
  from = "/index.html"
  to = "/"
  status = 200
  force = true
