services:
  - type: web
    name: bluejay
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --chdir backend --bind 0.0.0.0:$PORT

  - type: worker
    name: bluejay-trainer
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/train_from_logs.py
    schedule: "@every 48h"
