services:
  - type: web
    name: bluejay-backend
    env: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    autoDeploy: true

  - type: background
    name: brain-trainer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python train_from_logs.py
    autoDeploy: true
