services:
  - type: web
    name: bluejay-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true

  - type: background
    name: bluejay-auto-train
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python train_from_logs.py
    plan: free
    autoDeploy: true
    schedule: "0 0 */2 * *"  # every 2 days
