services:
  - type: web
    name: bluejay-web
    env: python
    plan: free
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn backend.main:app --bind 0.0.0.0:$PORT
    autoDeploy: true

  - type: worker
    name: bluejay-train-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python train_from_logs.py
    schedule: "0 */48 * * *"  # every 2 days
