services:
  - type: background
    name: brain-trainer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python train_from_logs.py
    autoDeploy: true
