services:
  - type: web
    name: bluejay
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --chdir backend --bind 0.0.0.0:$PORT

  - type: worker
    name: bluejay-conversation-trainer
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/train_from_logs.py
    schedule: "@every 1h"

  - type: worker
    name: bluejay-seo-trainer
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python dev_sync_seo.py
    schedule: "0 * * * *"

  - type: cron
    name: blog-generator
    env: python
    plan: starter
    schedule: "0,30 * * * *"
    buildCommand: ""
    startCommand: python3 docs/blog_pipeline.py
    envVars:
      - key: GIT_REMOTE
        value: https://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@github.com/Mrjonwells/bluejay.git
