[build]
  base = "frontend"
  publish = "./"
  command = "pip install -r requirements.txt && python ../dev_sync_seo.py && npm run build"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/chat"
  to = "https://bluejay-api.onrender.com/chat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
