[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"
  functions = "frontend/netlify/functions"  # If your functions are in the correct directory

[build.environment]
  VITE_BACKEND_URL = "your-backend-url"
  NODE_VERSION = "16"

[redirects]
  from = "/index.html"
  to = "/"
  status = 200
  force = true