[build]
  base = "frontend"
  command = "echo 'No build command required'"  # No build step needed
  publish = "/opt/build/repo/frontend"  # Path to frontend directory

[functions]
  directory = "backend/netlify/functions"  # Path to backend functions (if applicable)

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 200
  force = true

[env]
  VITE_BACKEND_URL = "your-backend-url"  # If you're using any environment variables