[build]
  publish = "frontend"
  command = ""

[functions]
  directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  autoLaunch = false