[build]
base = "frontend"  # Path to your frontend folder
command = "echo 'No build command required'"  # No need to build if not using npm or yarn
publish = "frontend/build"  # Where your built front-end assets are
functions = "netlify/functions"  # Specify function directory if applicable (even if it's empty)

[[redirects]]
from = "/index.html"
to = "/"
status = 200
force = true