[build]
  base = "bluejay/frontend"
  publish = "./"
  command = "pip install pytrends && python ../../dev_sync_seo.py || echo 'SEO sync failed — continuing...' && npm install && npm run build"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/chat"
  to = "https://bluejay-api.onrender.com/chat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
