name: Auto Blog Sync

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Git
        run: |
          git config --global user.email "bluejay@askbluejay.ai"
          git config --global user.name "BlueJay Bot"

      - name: Run Blog Pipeline
        run: |
          python3 frontend/blog_pipeline.py

      - name: Commit Changes
        run: |
          git add frontend/blogs/ frontend/blog.html
          git commit -m "Auto-sync SEO and blog updates from BlueJay" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push https://x-access-token:${{ secrets.BLUEJAY_PAT }}@github.com/Mrjonwells/bluejay.git
