name: Generate Blog Post

on:
  schedule:
    - cron: "0 13 * * *"  # 6am PST daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo without GitHub bot creds
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run blog pipeline
        run: python3 docs/blog_pipeline.py
        continue-on-error: false

      - name: Update sitemap
        run: python3 docs/sitemap_updater.py

      - name: Push blog with classic PAT
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "BlueJay Bot"
          git config --global user.email "bot@askbluejay.ai"
          git remote set-url origin https://Mrjonwells:${GIT_AUTH_TOKEN}@github.com/Mrjonwells/bluejay.git
          git pull origin main --rebase || true
          git add docs/blogs/*.html docs/blogs/index.json docs/sitemap.xml
          git commit --no-verify -m "Auto-blog update from GitHub Action" || echo "::notice::Nothing to commit"
          git push origin main
