name: Generate Blog Post

on:
  schedule:
    - cron: "0,30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REMOTE: https://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@github.com/Mrjonwells/bluejay.git

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run blog pipeline
        run: python3 docs/blog_pipeline.py

      - name: Push changes
        run: |
          git config user.name "BlueJay Bot"
          git config user.email "bot@askbluejay.ai"
          git add .
          git commit -m "Auto-blog update from GitHub Action" || echo "Nothing to commit"
          git push origin main
