name: Sync BlueJay Blog

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run blog generator
        run: python backend/generators/blog_generator_runner.py

      - name: Set up Git config
        run: |
          git config user.name "BlueJay Bot"
          git config user.email "bluejay@askbluejay.ai"
          git remote add origin https://Mrjonwells:${{ secrets.GITHUB_TOKEN }}@github.com/Mrjonwells/bluejay.git

      - name: Pull latest with rebase
        run: git pull origin main --rebase || true

      - name: Commit and push changes
        run: |
          git add frontend/blog.html frontend/blogs/*.html
          git commit -m "Auto-sync SEO and blog updates from BlueJay" || echo "No changes to commit"
          git push origin HEAD:main
