name: Blog Auto Sync

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install openai

      - name: Run Blog Generator
        run: python3 backend/generators/blog_generator_runner.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Set up Git config
        run: |
          git config --global user.email "bluejay@askbluejay.ai"
          git config --global user.name "BlueJay Bot"
          git remote add origin https://Mrjonwells:${{ secrets.GITHUB_TOKEN }}@github.com/Mrjonwells/bluejay.git

      - name: Commit and Push Changes
        run: |
          git add frontend/blogs/*.html frontend/blog.html || true
          git commit -m "Auto-sync SEO and blog updates from BlueJay" || echo "No changes to commit"
          git push --force origin HEAD:main
