name: Update External Blog Topics

on:
  schedule:
    - cron: "0 2 * * 1,4"  # Twice weekly: Mondays & Thursdays 2am UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Refresh external topics
        run: python3 backend/seo/external_topic_feeder.py

      - name: Commit updated topics
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "BlueJay Topic Bot"
          git config --global user.email "bot@askbluejay.ai"
          git remote set-url origin https://Mrjonwells:${GIT_AUTH_TOKEN}@github.com/Mrjonwells/bluejay.git
          git pull origin main --rebase || true
          git add backend/seo/external_topics.json
          git commit --no-verify -m "Updated external blog topics" || echo "::notice::No topic updates"
          git push origin main
